name: Arbetsrattsappen
favicon: null
layout_spectrum: 0.3749123848974705
typography_spectrum: 0.828098684316501
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6466598126571625
  lightness: 0.36737943231128156
  saturation: 0.8699334426783025
  rhythmicContrast: 0.7374466208275408
purpose: []
